### ISSUE TITLE
Why did the authors choose to compare the ImageMol model, which was pretrained on 10 million data points from the PubChem dataset, with the ImageMol_NonPretrained model that uses a ResNet18 architecture with randomly initialized weights? It seems potentially unfair as the non-pretrained model might be at a disadvantage. Additionally, could you clarify how the ImageMol_NonPretrained model achieved a higher AUC than Jure’s GNN in some cases?  Thank you so much

### ISSUE THREAD

**Issue by ldkien-304** [HongxinXiang/ImageMol#19]

**Comment by HongxinXiang** [comment]
1. The purpose of using ImageMol with and without pretraining is to show the effectiveness of the pretraining. Obviously, the pre-trained model should be better than the non-pre-trained model.
2. For the second question, I'm sorry I can't answer your question because we haven't done a specific analysis on why ImageMol_NonPretrained is better than Jure's GNN.
